
services:
  backend:
    build:
      context: ./  # ajuste para o diretório onde está o Dockerfile do backend
    container_name: backend_fastapi
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:topedro2003@db/mlaas_db
    depends_on:
      - db


  db:
    image: mysql:8.0
    container_name: mlaas_db
    environment:
      MYSQL_ROOT_PASSWORD: topedro2003
      MYSQL_DATABASE: mlaas_db
    ports:
    - "3307:3306"  # Mapeia a porta 3306 do container para a porta 3307 no host
    volumes:
    - db_data:/var/lib/mysql

  #ml_service:
   # build:
  #    context: ./MLService  # diretório do container que roda o modelo ML
 #   container_name: ml_service
 #   ports:
 #     - "8001:8000"  # ou a porta que você configurar para esse serviço

volumes:
  db_data:
